# Generated by Django 3.2.8 on 2021-10-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='team member')),
                ('number', models.IntegerField(verbose_name='number')),
                ('email', models.CharField(max_length=50, verbose_name='team member')),
                ('position', models.CharField(max_length=50, verbose_name='member position')),
                ('bdate', models.DateTimeField(verbose_name='birth date')),
            ],
        ),
    ]
