# Generated by Django 3.2.8 on 2021-11-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.IntegerField(default=11, verbose_name='tour_duration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.FileField(default=11, upload_to='tours/'),
            preserve_default=False,
        ),
    ]
