# Generated by Django 3.2.8 on 2021-11-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_tour_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
