# Generated by Django 3.2.8 on 2021-11-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_tour_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.FileField(upload_to='tours/'),
        ),
    ]
